#ifndef SUDOKU_INTERNAL_INTEL_GNR_H
#define SUDOKU_INTERNAL_INTEL_GNR_H

// Processors (Intel(R) Xeon(R) Gold 6438Y+, DDR5)

#define SBDR_LOWER_BOUND_ 310
#define SBDR_UPPER_BOUND_ 450

#define REFRESH_CYCLE_LOWER_BOUND_ 450
#define REFRESH_CYCLE_UPPER_BOUND_ 1100
#define BANK_GROUP_THRESHOLD_ 290
#define REGULAR_REFRESH_INTERVAL_THRESHOLD_ 3000

#define PCI_OFFSET_UPPER_BOUND_ 0x0
#define PCI_OFFSET_LOWER_BOUND_ 0x0

#endif  // SUDOKU_INTERNAL_INTEL_GNR_H
