#ifndef SUDOKU_INTERNAL_INTEL_CORE_ULTRA_2TH_DDR5_H
#define SUDOKU_INTERNAL_INTEL_CORE_ULTRA_2TH_DDR5_H

// Processors (Intel Core Ultra Arrow Lake, Ultra 9 285K)
#define SBDR_LOWER_BOUND_ 600 // 5600
// #define SBDR_LOWER_BOUND_ 530 // 4800
#define SBDR_UPPER_BOUND_ 800 //5600
// #define SBDR_UPPER_BOUND_ 730
#define REFRESH_CYCLE_LOWER_BOUND_ 500
#define REFRESH_CYCLE_UPPER_BOUND_ 1100
#define BANK_GROUP_THRESHOLD_ 500
#define REGULAR_REFRESH_INTERVAL_THRESHOLD_ 5500

// #define PCI_OFFSET_UPPER_BOUND_ 0x0
// #define PCI_OFFSET_LOWER_BOUND_ 0x0

#define PCI_OFFSET_UPPER_BOUND_ 0x0
// #define PCI_OFFSET_UPPER_BOUND_ 0x80000000
#define PCI_OFFSET_LOWER_BOUND_ 0x0
// #define PCI_OFFSET_LOWER_BOUND_ 0xA0000000

#endif  // SUDOKU_INTERNAL_INTEL_CORE_ULTRA_2TH_DDR5_H
