#ifndef SUDOKU_INTERNAL_INTEL_XEON_PLATINUM_8260_DDR4_H
#define SUDOKU_INTERNAL_INTEL_XEON_PLATINUM_8260_DDR4_H

// Processors (Intel Cascade Lake Xeon Platinum 8260 @ 2.4GHz, DDR4)
#define SBDR_LOWER_BOUND_ 350 
#define SBDR_UPPER_BOUND_ 500
#define REFRESH_CYCLE_LOWER_BOUND_ 500
#define REFRESH_CYCLE_UPPER_BOUND_ 1100
#define BANK_GROUP_THRESHOLD_ 290
#define REGULAR_REFRESH_INTERVAL_THRESHOLD_ 5000

#define PCI_OFFSET_UPPER_BOUND_ 0x0
#define PCI_OFFSET_LOWER_BOUND_ 0x0

#endif  // SUDOKU_INTERNAL_INTEL_XEON_PLATINUM_8260_DDR4_H
